version: "3.9"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: teacher_student_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d"]
      interval: 5s
      timeout: 5s
      retries: 5

  #teacher-student-be
  teacher-student-api:
    build:
      context: ./be
      dockerfile: dockerfile
    container_name: teacher-student-api
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      HOST: ${HOST}
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - mysql-db
    ports:
      - "${BE_SERVICE_PORT}:${PORT}"

volumes:
  db_data:
